### ISSUE TITLE
Use special comment syntax?

### ISSUE THREAD

**Issue by marijnh** [adrianheine/gettypes#10]
I guess that technically, getdocs does use special syntax (matching `//\s*::`) to distinguish doc comments from other comments. I think doing away with that entirely might not be a good idea—it makes it easy to accidentally add comments that get interpreted as docs even though they weren't meant as such, and makes it less obvious to the reader of the code that something is part of the rendered documentation.

Dart and C# support both `/**` and `///` syntax. That could work. A thing that only has to add noise to the first line could also be nice (maybe `//!`?) but I suppose that'd make alignment awkward due to the extra character on the first line.

**Comment by marijnh** [comment]
[Godoc](https://blog.golang.org/godoc-documenting-go-code) _does_ use plain comments, using something similar to what we are doing now, so that can be made to work too. But in general the fact that Go does something isn't proof that it's good taste ;)

**Comment by adrianheine** [comment]
You implemented `///` in #15.
