### ISSUE TITLE
Types instead of syntax trees?

### ISSUE THREAD

**Issue by marijnh** [adrianheine/gettypes#11]
You mentioned that you thought maybe it would have been a better approach to base the tool on the type datastructures rather than the syntax tree that TypeScript spits out. I'm getting some issues which come from `mapType`, which has a comment "this is so bad", which I guess means it's not really in a shape that you're happy with.

Could you fill me in on the considerations of using types vs syntax trees? Maybe we can use this issue to reach a conclusion on that so that we know which direction to go in.

**Comment by adrianheine** [comment]
Implemented in #15.
