### ISSUE TITLE
Breaking JSON format change?

### ISSUE THREAD

**Issue by marijnh** [adrianheine/gettypes#12]
The new requirements introduced by the TS type system are showing quite a few limitations and general weaknesses in the JSON format from getdocs. It may be worthwhile to redesign the output format (and then later follow up with a major new version of getdocs and builddocs to align them with the new format).

These are some of the issues:

 - `typeParams` means two things (type arguments to an instance of a parameterized type, and actual type parameters of a generic interface, class or type alias)

 - The format conflates symbol types and the types of the things the symbols point at. The `type` property may hold an actual type name, but it can also hold `"class"` or `"interface"` to indicate that this is a class/interface name. This becomes more problematic with type aliases and enums. I think we should have _different_ properties to describe the symbol type (const/class/interface/alias/property/etc) and the associated _type_ (array/number/EditorView/etc).

 - The flat namespace model for typenames is very naive and if we're going to overhaul this we should probably think about that too. It's unlikely that a given module will export multiple things with the same name, but it's quite possible for it to, for example, import things with the same name from multiple external modules, and have such types show up in the output.
  A possible approach here would be to have more abstract source data for each type. Sources can be either local (in which case the HTML link should be to an id in the document itself) or remote, in which case the HTML generator needs to somehow map the source data to a URL (which I guess will involve custom code).
   Not sure if we want to support renaming of ambiguous types.

I don't think being able to represent all types that TypeScript can represent should be a goal, but aligning more closely to how they structure types, so that our output can be easily readable by people familiar with TypeScript, would be good.

What do you think?

**Comment by marijnh** [comment]
(I'd also like to move `staticProperties` to `properties` and put the instance properties in `instanceProperties`.)

**Comment by marijnh** [comment]
(And rename `.constructor` to something that doesn't exist on `Object.prototype`, like `construct`.)

**Comment by adrianheine** [comment]
What's the current status here? I guess you implemented most of these things in builddocs#v1?

**Comment by marijnh** [comment]
Yes, I did, though my approach to named types might still not cover renaming scenarios very well. I guess we can close this and reevaluate when we hit new issues.
