### ISSUE TITLE
No differentiation between type parameters on whole type and on callable signature

### ISSUE THREAD

**Issue by adrianheine** [adrianheine/gettypes#17]
```ts
interface A<X> {
  <Y>(y: Y): [X, Y]
}
```
This is probably a rather academic example and could imho only be worked around by turning the callable signature into a separate property.

**Comment by marijnh** [comment]
This does make a difference for overloaded functions that have different sets of type parameters per overload. Patch 9b30df824d9b3 makes this change—signatures as a separate collection also makes it a lot easier to add call and constructor signatures to object types.
