### ISSUE TITLE
Why are internal/private constructors emitted?

### ISSUE THREAD

**Issue by marijnh** [adrianheine/gettypes#2]
The logic under `ts.SyntaxKind[prop.kind] == "Constructor"` _does_ check for private/internal, but then seems to go ahead and emit the constructor anyway. It seems to do the right way if I simply continue immediately without adding anything for private constructors. Am I missing something?

**Comment by adrianheine** [comment]
For private constructors, this runs:

https://github.com/adrianheine/gettypes/blob/cd1637d3d91392231274d37a9b74ff804b4ae93e/src/index.js#L266

That should hide them from the output. They are not completely skipped for handling parameter properties.

**Comment by marijnh** [comment]
Weird, that isn't working for me—I'm getting them in the JSON (and thus builddocs) output. Will dig into this when I get home next week.

**Comment by adrianheine** [comment]
Does this work for you (now)?

**Comment by marijnh** [comment]
Yes, they shouldn't be in the current output anymore.
